// константы

export const ACTION_TYPE = {
	SET_TODOS: "SET_TODOS",
	LOAD_START: "LOAD_START",
	LOAD_END: "LOAD_END",
	ADD_TODO: "ADD_TODO",
	EDIT_TODO: "EDIT_TODO",
	SET_SEARCH_PHRASE: "SET_SEARCH_PHRASE",
	SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
	SET_IS_ALPHABET_SORTING: "SET_IS_ALPHABET_SORTING",
	REMOVE_TODO: "REMOVE_TODO",
	UPDATE_TODO: "UPDATE_TODO",
};
